### ISSUE TITLE
Need to improve runDockerContainer.sh to stop/remove existing running container

### ISSUE THREAD

**Issue by linuxep** [linuxep/lepv#1]
Currently we have a script to start a new LEPV Docker container ( which is runDockerContainer.sh ),  in this script, before running a new container, it tries to stop and remove any existing container of the same image, with command like this:

docker ps -a | awk '{ print $1,$2 }' | grep linuxep/lepv0.1 | awk '{print $1 }' | xargs -I {} docker stop {} | xargs -I {} docker rm {}

The problem is, sometimes when running the first command of the chain( "docker ps -a" ), its IMAGE column does not show up as "linuxep/lepv0.1", but as image ID, thus this script fails.

C02LJ0U4FFT1:workspace mxu$ docker ps  ( IMAGE shown as "linuxep/lepv0.1")
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
8f4d953caf74        linuxep/lepv0.1     "uwsgi --ini lepv_doc"   3 days ago          Up 3 days           0.0.0.0:8889->8889/tcp   big_boyd

C02LJ0U4FFT1:workspace mxu$ docker ps  ( IMAGE NOT shown as "linuxep/lepv0.1")
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
8f4d953caf74        8f4d953caec8     "uwsgi --ini lepv_doc"   3 days ago          Up 3 days           0.0.0.0:8889->8889/tcp   big_boyd

I would like the script being fixed, so any existing running LEPV container can be stop/removed no matter the "IMAGE" of a container shown up as IMAGE name or as IMAGE ID.

**Comment by crook** [comment]
docker ps -a -q

**Comment by linuxep** [comment]
can you please make sure you understand the issue?

**Comment by crook** [comment]
please think over the workflow, if you want to remove the '<NAME>/<ID> 'image.

Steps:
1. GET the image ID form 'docker images <NAME>'
2. filter NAME or ID from 'docker ps -a' comand.

Will this 'grep NAME|ID' string work?

**Comment by linuxep** [comment]
Fixed.

the "image name of a container might become "out of date" if that image has been rebuilt, in which case the image name for that container becomes the image ID of the "old" image.

I've updated the script to stop/remove container based on ports.
