### ISSUE TITLE
no date show chart

### ISSUE THREAD

**Issue by chowyu08** [linuxep/lepv#27]
![image](https://cloud.githubusercontent.com/assets/16483518/21217408/f77ddcd0-c2e6-11e6-9098-34b3149091c5.png)

URLs may not match requestId.

![image](https://cloud.githubusercontent.com/assets/16483518/21217478/5be773de-c2e7-11e6-8ef7-50ae626bccfe.png)

**Comment by linuxep** [comment]
can you please provide more information:

where is your LEPD running at?

**Comment by chowyu08** [comment]
yes. 
I run lepd im my vm with the ip 192.168.156.80, and I run lepv by python manager runserver in my windows7, the lepv connnect 192.168.156..80, connect success.  
### lepd:
![image](https://cloud.githubusercontent.com/assets/16483518/21388416/2630fede-c7b7-11e6-9b14-d58b50434d5a.png)

### lepv:
![image](https://cloud.githubusercontent.com/assets/16483518/21388441/3b335156-c7b7-11e6-9d08-1d760f95870d.png)

there are many errors of 404.

### web:
![image](https://cloud.githubusercontent.com/assets/16483518/21388503/8ab7f380-c7b7-11e6-8224-350a3b7337a9.png)

![image](https://cloud.githubusercontent.com/assets/16483518/21388555/ba043b8a-c7b7-11e6-9a0e-265c980b3a0b.png)
only have the cpu and memory info
only **Average Load** **CPU TOP** **消耗的内存、Page Cahe(Buffers, Cached)和空闲的内存** have data.

![image](https://cloud.githubusercontent.com/assets/16483518/21388661/3ef11188-c7b8-11e6-9e61-c648bb1220e5.png)

**Comment by chowyu08** [comment]
if I connect to www.linuxxueyuan.com , everything is ok.

**Comment by linuxep** [comment]
This is because the VM you were running LEPD against is NOT well configured to run LEPD... 

LEPD requires some third-party libraries( for C ) and some tool installation to be fully functional, this is why you can see some data on UI, but not all of them.

we will improve the Dockerfile for LEPD later on.
