### ISSUE TITLE
Faulty injection:heavy load of network irq and softirq in a single core

### ISSUE THREAD

**Issue by chensong2000** [linuxep/lepv#33]
hrtimer

**Comment by 21cnbao** [comment]
i really did a hrtimer-based virt net: https://github.com/21cnbao/training/blob/master/kernel/drivers/net/lepeth.c
but it seems it doesn't work for RPS/RFS.
instead, we move to use a real pcduino board with high iperf net load:
http://mp.weixin.qq.com/s/FQKFRcMNDk6VE7ihnnvBPw

it shows a great demo for load-balance.

**Comment by chensong2000** [comment]
i read http://mp.weixin.qq.com/s/FQKFRcMNDk6VE7ihnnvBPw and it perfectly demonstrates the value of lep.
