### ISSUE TITLE
Logic to compare two dictionaries

### ISSUE THREAD

**Issue by macxu** [linuxep/lepv#49]
Need a logic/method to implement a logic to compare two dictionaries with Python 3.5+

def compare_dicts( dict_1, dict_2):
    # if dict_1 equals to dict_2, return 0.

    #  if dict_1 contains dict_2, return 1.

    # if dict_2 contains dict_1, return -1.

    # otherwise return 2

show your code, and your tests for it.

**Comment by Oscer2016** [comment]
method:
#!/usr/bin/env python3

def compare_dicts(dict_1, dict_2):
    # 将字典的键存入集合中
    tdict_1 = set(dict_1)
    tdict_2 = set(dict_2)

    flag = 2
    
    # 如果键完全相等，然后判断键对应的值是否相等
    if tdict_1 == tdict_2:
        for key in tdict_1:
            if dict_1[key] != dict_2[key]:
                return 2
        flag = 0
    # 如果dict_1的键包含dict_2的键，然后判断键对应的值是否相等
    elif tdict_1 > tdict_2:
        for key in dict_2:
            if dict_1[key] != dict_2[key]:
                return 2
        flag = 1
    # 如果dict_2的键包含dict_1的键，然后判断键对应的值是否相等
    elif tdict_1 < tdict_2:
        for key in dict_1:
            if dict_1[key] != dict_2[key]:
                return 2
        flag = -1

    return flag


test_case:
#!/usr/bin/env python3

import unittest
import dict

class TestRelatioinCase(unittest.TestCase):

    def test_relation(self):
        dict_1 = {}
        dict_2 = {}
        dict_3 = {'key1':'value1', 'key2':'value2'}
        dict_4 = {'k1':'value1', 'key2':'value2'}
        dict_5 = {'key1':'v1', 'key2':'value2'}
        dict_6 = {'key1':'value1', 'key2':'value2', 'key3':'value3'}
        
        ret_1 = dict.cmp(dict_1, dict_2)
        self.assertEqual(ret_1, 0)
        ret_2 = dict.cmp(dict_2, dict_3)
        self.assertEqual(ret_2, -1)
        ret_3 = dict.cmp(dict_3, dict_2)
        self.assertEqual(ret_3, 1)
        ret_4 = dict.cmp(dict_3, dict_4)
        self.assertEqual(ret_4, 2)
        ret_5 = dict.cmp(dict_3, dict_5)
        self.assertEqual(ret_5, 2)
        ret_6 = dict.cmp(dict_3, dict_6)
        self.assertEqual(ret_6, -1)
        ret_7 = dict.cmp(dict_6, dict_3)
        self.assertEqual(ret_7, 1)

if __name__ == '__main__':
    unittest.main()

run_result:
[hp@pavilion 23:21 ~]$ python3.6 test_case.py 
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK

**Comment by Oscer2016** [comment]
# method:
```
# filename:dict.py
#!/usr/bin/env python3

def compare_dicts(dict_1, dict_2):
    # Store the keys of the dictionary in the collection,
    # if dict_1 is None, set(dict_1) will return empty collection.
    tdict_1 = set(dict_1)
    tdict_2 = set(dict_2)

    flag = 2

    # If the keys are exactly equal, and then judge whether
    # the value of the key corresponding to the equal.
    if tdict_1 == tdict_2:
        flag = 0
        for key in tdict_1:
            if dict_1[key] != dict_2[key]:
                if isinstance(dict_1[key], dict):
                    flag = compare_dicts(dict_1[key], dict_2[key])
                else:
                    return 2
        return flag
    
    # If the keys of dict_1 contains the keys of dict_2, and then
    # judge the value of the dict_2's key corresponding to the equal.
    elif tdict_1 > tdict_2:
        flag = 1
        for key in dict_2:
            if dict_1[key] != dict_2[key]:
                if isinstance(dict_1[key], dict):
                    flag = compare_dicts(dict_1[key], dict_2[key])
                else:
                    return 2
        return flag

    # If the keys of dict_2 contains the keys of dict_1, and then
    # judge the value of the dict_1's key corresponding to the equal.
    elif tdict_1 < tdict_2:
        flag = -1
        for key in dict_1:
            if dict_1[key] != dict_2[key]:
                if isinstance(dict_1[key], dict):
                    flag = compare_dicts(dict_1[key], dict_2[key])
                else:
                    return 2
    return flag

```

# test_case:
```
#!/usr/bin/env python3

import unittest
import dict

class TestRelatioinCase(unittest.TestCase):

    def test_equal(self):
        dict_1 = {}
        dict_2 = {}
        dict_3 = {'key1':'value1', 'key2':'value2'}
        
        ret_1 = dict.compare_dicts(dict_1, dict_2)
        ret_2 = dict.compare_dicts(dict_3, dict_3)
        self.assertEqual(ret_1, 0)
        self.assertEqual(ret_2, 0)

    def test_contains(self):
        dict_1 = {'key1':'value1', 'key2':'value2'}
        dict_2 = {'key1':'value1', 'key2':'value2', 'key3':'value3'}
        dict_3 = {'key1':{'k1':'v1'}, 'key2':'value2'}
        dict_4 = {'key1':{'k1':'v1', 'k2':'v2'}, 'key2':'value2'}
        
        ret_1 = dict.compare_dicts(dict_2, dict_1)
        ret_2 = dict.compare_dicts(dict_4, dict_3)
        self.assertEqual(ret_1, 1)
        self.assertEqual(ret_2, 1)
    
    def test_contained(self):
        dict_1 = {(1,2):{'k1':'v1'}, 'key2':'value2'}
        dict_2 = {(1,2):{'k1':'v1', 'k2':'v2'}, 'key2':'value2', 'key3':'value3'}
        
        ret_1 = dict.compare_dicts(dict_1, dict_2)
        self.assertEqual(ret_1, -1)
   
    def test_other(self):
        dict_1 = {'key1':'value2', 'key2':'value1'}
        dict_2 = {'key1':'value1', 'key2':'value2'}
        dict_3 = {'key1':{'k1':'v1'}, 'key2':'value2'}
        dict_4 = {'key1':{'k2':'v2'}, 'key2':'value2'}
        
        ret_1 = dict.compare_dicts(dict_1, dict_2)
        ret_2 = dict.compare_dicts(dict_3, dict_4)
        self.assertEqual(ret_1, 2)
        self.assertEqual(ret_2, 2)

if __name__ == '__main__':
    unittest.main()

```

# run_result:
```
[hp@pavilion 15:43 ~]$ python3 test_case.py 
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
```
