### ISSUE TITLE
refactor LEPV, stop sending request from Javascript

### ISSUE THREAD

**Issue by macxu** [linuxep/lepv#75]
We've moved from Restful API to SocketIO for LEPV, we can leverage the feature SocketIO to get the best out of it.

1. SocketIO can "push" message to web clients, so we can leverage this feature.
2. SocketIO can "push" messages by "rooms", we should name the rooms by the LEPD server names, and broadcast related data by 'rooms'.
3. We can how to use the event/message for database operations because we don't want to block the main process.
4. We should consider do the "timing" by Flask/Python rather than the Javascript, but be careful not to 'block' the main thread.

**Comment by macxu** [comment]
this is a very good tutorial:
https://flask-socketio.readthedocs.io/en/latest/

you can get all the information you need to get this story done.

**Comment by chowyu08** [comment]
start in branch request-in-python
