### ISSUE TITLE
07/12/2019 testing issues

### ISSUE THREAD

**Issue by chensong2000** [linuxep/lepv#84]
1，中断图形没有变化和数据，我在lepv里没有搜索到如下调用
GetProcInterrupts
GetProcSoftirqs
GetCmdIrqInfo

2，IO趋势图也没有变化，不知道调用的是哪一个，我看到有调用Iostat
3, 有好几个NET_TX的趋势图
4，我做了一个lepd的守护者进程，就是lepd要是死了就再启动一个，但启动之后，发现lepv并没有和新的lepd通信
5,cpu User + System + Nice
6,cpu idle趋势图也没有变化

**Comment by chowyu08** [comment]
关机是问题4， 没有重新连接应该，这个我看一下

**Comment by chensong2000** [comment]
好的，如果4可以的话，那就可以正式启用多线程了，效率会高好多。

**Comment by chensong2000** [comment]
其他的问题麻烦也看看啊，图没有变化，demo的效果就不会很好。
